# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'campuses'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.Campus'),
        ),
    ]
