# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_auto_20170821_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('subround_number', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
