# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0004_admissionproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('slots', models.IntegerField()),
                ('slots_comments', models.TextField(blank=True)),
                ('detail_items_csv', models.TextField()),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.AdmissionProject')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.Faculty')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
