# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0005_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='short_descriptions',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='admissionround',
            name='admission_dates',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionround',
            name='short_descriptions',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
