# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0008_admissionproject_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionproject',
            name='admission_rounds',
        ),
    ]
