# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0009_remove_admissionproject_admission_rounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProjectRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_dates', models.CharField(max_length=100)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.AdmissionProject')),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.AdmissionRound')),
            ],
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='admission_rounds',
            field=models.ManyToManyField(through='majors.AdmissionProjectRound', to='majors.AdmissionRound'),
        ),
    ]
