# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0012_major_simplified_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='column_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='major_description_list_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='major_table_header_precomputed',
            field=models.TextField(blank=True),
        ),
    ]
