# Generated by Django 2.2.17 on 2020-11-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0014_auto_20201110_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='max_num_selections',
            field=models.IntegerField(default=1, verbose_name='จำนวนสาขาที่เลือกได้'),
        ),
    ]
