# Generated by Django 2.2.17 on 2020-11-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0015_auto_20201114_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='default_round_number',
            field=models.IntegerField(default=0, verbose_name='รอบ (default)'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='table_header_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชื่อสั้นมากแสดงหัวตาราง'),
        ),
    ]
