# Generated by Django 3.2.7 on 2024-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0016_auto_20201122_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='display_rank',
            field=models.IntegerField(default=0, verbose_name='สำหรับใช้เรียงรายการ'),
        ),
    ]
