# Generated by Django 2.2.17 on 2020-11-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0014_auto_20201110_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('additional_description', models.CharField(blank=True, max_length=100)),
                ('additional_condition', models.CharField(blank=True, max_length=500)),
                ('curriculum_majors_json', models.TextField(blank=True)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.AdmissionProject')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='majors.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['cupt_code'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('primary_order', models.IntegerField()),
                ('secondary_order', models.IntegerField(default=0)),
                ('criteria_type', models.CharField(max_length=30)),
                ('score_type', models.CharField(max_length=30)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('relation', models.CharField(blank=True, max_length=30, null=True)),
                ('admission_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.AdmissionCriteria')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='criteria.ScoreCriteria')),
            ],
            options={
                'ordering': ['primary_order', 'secondary_order'],
            },
        ),
        migrations.CreateModel(
            name='MajorCuptCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=30)),
                ('program_type', models.CharField(max_length=30)),
                ('program_type_code', models.CharField(max_length=5)),
                ('major_code', models.CharField(blank=True, max_length=5)),
                ('title', models.TextField()),
                ('major_title', models.TextField(blank=True, null=True)),
                ('component_weight_type', models.CharField(blank=True, max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.Faculty')),
            ],
            options={
                'ordering': ['program_type_code', 'program_code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumMajorAdmissionCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField()),
                ('version', models.IntegerField(default=1)),
                ('admission_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.AdmissionCriteria')),
                ('curriculum_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.CurriculumMajor')),
            ],
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='admission_criterias',
            field=models.ManyToManyField(through='criteria.CurriculumMajorAdmissionCriteria', to='criteria.AdmissionCriteria'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='admission_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.AdmissionProject'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='cupt_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.MajorCuptCode'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.Faculty'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='majors.Major'),
        ),
        migrations.AddConstraint(
            model_name='majorcuptcode',
            constraint=models.UniqueConstraint(fields=('program_code', 'major_code'), name='unique_program_major'),
        ),
    ]
