# Generated by Django 2.2.17 on 2020-11-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0015_auto_20201114_0422'),
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='majors.Campus'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='majors.Campus'),
        ),
    ]
