# Generated by Django 2.2.17 on 2020-11-16 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0015_auto_20201114_0422'),
        ('criteria', '0002_auto_20201116_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcuptcode',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='majors.Campus'),
        ),
    ]
