# Generated by Django 2.2.17 on 2020-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_majorcuptcode_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcuptcode',
            name='admission_project_list',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
