# Generated by Django 2.2.17 on 2020-11-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0005_admissioncriteria_min_scores_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='scoring_scores_json',
            field=models.TextField(blank=True),
        ),
    ]
