# Generated by Django 2.2.17 on 2021-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_admissioncriteria_scoring_scores_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummajoradmissioncriteria',
            name='imported_slots',
            field=models.IntegerField(default=0),
        ),
    ]
