# Generated by Django 3.2.13 on 2022-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0007_curriculummajoradmissioncriteria_imported_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='additional_interview_condition',
            field=models.TextField(blank=True),
        ),
    ]
