# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('more_link_text', models.CharField(blank=True, max_length=100, verbose_name='ข้อความบนลิงก์')),
                ('more_link_url', models.CharField(blank=True, max_length=100, verbose_name='ลิงก์อ่านต่อ')),
                ('attachment', models.FileField(blank=True, upload_to='announcements/%Y/%m/%d/', verbose_name='ไฟล์สำหรับดาวน์โหลด')),
            ],
        ),
    ]
