# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, verbose_name='วันเวลาที่ประกาศ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='แสดงผลหรือไม่'),
        ),
    ]
