# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0013_auto_20170918_0352'),
        ('main', '0002_auto_20170830_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='admission_round',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='majors.AdmissionRound'),
        ),
    ]
