# Generated by Django 3.2.7 on 2023-02-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_announcement_admission_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='has_extra_indent',
            field=models.BooleanField(default=False, verbose_name='ย่อหน้าเพิ่มเติมหรือไม่'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='rank',
            field=models.IntegerField(default=1000, verbose_name='ลำดับในการแสดง'),
        ),
    ]
