# Generated by Django 4.0.10 on 2026-07-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230216_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['rank', '-created_date']},
        ),
    ]
